"""Director plans — idea to scene list for MotionForge."""

from __future__ import annotations


ELISHA_SCENES = [
    {
        "scene_id": 1,
        "duration": 6,
        "narration": "Dawn over Dothan. The city is already surrounded.",
        "visual_prompt": "Elisha, elderly Middle Eastern prophet, gray hair, long gray beard, earth-tone robe, stone doorway at blue hour. 9:16, 35mm, no text.",
        "subject_motion": "Elisha stands still in the doorway; servant’s shoulders rise once.",
        "camera_motion": "slow dolly-in",
        "environment_motion": "distant dust in the valley; oil-lamp flame flickers once",
        "lighting_motion": "stable blue hour with one warm lamp",
        "facial_motion": "calm face; one blink; preserve identity",
        "camera": "slow dolly-in",
        "location": "Elisha’s doorway, Dothan",
        "lighting": "blue hour plus oil lamp",
        "sound_design": "wind, distant camp",
        "transition": "cut",
        "characters": ["Elisha", "Servant"],
    },
    {
        "scene_id": 2,
        "duration": 6,
        "narration": "The servant ran to the rooftop—and his courage failed.",
        "visual_prompt": "Young Levantine servant on a mud rooftop overlooking an Aramean siege camp at sunrise. 9:16, 24mm, no text.",
        "subject_motion": "One step to the parapet; grips stone.",
        "camera_motion": "pan-left",
        "environment_motion": "tent cloth and horse tails in wind",
        "lighting_motion": "hard sunrise, stable",
        "facial_motion": "eyes widen; jaw tightens; preserve face",
        "camera": "pan-left",
        "location": "rooftop, Dothan",
        "lighting": "sunrise raking light",
        "sound_design": "horses, metal, wind",
        "transition": "cut",
        "characters": ["Servant"],
    },
    {
        "scene_id": 3,
        "duration": 5,
        "narration": "Alas, my master—what shall we do?",
        "visual_prompt": "Close portrait of the servant pleading; Elisha soft in background. 9:16, 85mm, no text.",
        "subject_motion": "Almost still; speech only.",
        "camera_motion": "static",
        "environment_motion": "dust motes in window light",
        "lighting_motion": "stable side window key",
        "facial_motion": "brow knit, lips form the plea; preserve structure",
        "camera": "static",
        "location": "house interior",
        "lighting": "side window",
        "sound_design": "close whispered panic",
        "transition": "cut",
        "characters": ["Servant", "Elisha"],
    },
    {
        "scene_id": 4,
        "duration": 7,
        "narration": "Do not fear. Those who are with us are more than those who are with them.",
        "visual_prompt": "Elisha medium shot, gray beard, earth-tone robe, hand slightly raised. 9:16, 50mm, no text.",
        "subject_motion": "Right hand rises a few inches, then holds.",
        "camera_motion": "slow dolly-in",
        "environment_motion": "cloak hem barely moves",
        "lighting_motion": "warm lamp, stable",
        "facial_motion": "steady gaze; preserve Elisha identity",
        "camera": "slow dolly-in",
        "location": "house interior",
        "lighting": "warm practicals",
        "sound_design": "grounded voice",
        "transition": "dissolve",
        "characters": ["Elisha", "Servant"],
    },
    {
        "scene_id": 5,
        "duration": 6,
        "narration": "Then Elisha prayed: Lord, open his eyes, that he may see.",
        "visual_prompt": "Elisha in profile, eyes lifted, hands open, window beam. 9:16, 40mm, no text.",
        "subject_motion": "Lips move in prayer; fingers uncurl slowly.",
        "camera_motion": "crane",
        "environment_motion": "dust motes rise in the beam",
        "lighting_motion": "gold rim intensifies about 20 percent",
        "facial_motion": "eyelids lower then lift; preserve face",
        "camera": "crane",
        "location": "interior by window",
        "lighting": "window beam plus gold rim",
        "sound_design": "prayer, tonal swell",
        "transition": "match cut",
        "characters": ["Elisha"],
    },
    {
        "scene_id": 6,
        "duration": 8,
        "narration": "And the Lord opened the eyes of the young man.",
        "visual_prompt": "Servant on rooftop; horses and chariots of fire on the ridges; earthly camp below. 9:16, 28mm, no text.",
        "subject_motion": "Head turns to the mountain; half-step back.",
        "camera_motion": "orbit",
        "environment_motion": "heat-shimmer; host holds formation",
        "lighting_motion": "gold volume breathes up 15 percent",
        "facial_motion": "pupils widen; fear becomes awe; preserve face",
        "camera": "orbit",
        "location": "rooftop and ridges",
        "lighting": "dawn plus heavenly gold",
        "sound_design": "air rush, distant thunder",
        "transition": "hold",
        "characters": ["Servant"],
    },
    {
        "scene_id": 7,
        "duration": 8,
        "narration": "The mountain was full of horses and chariots of fire, all around Elisha.",
        "visual_prompt": "Epic wide of fiery host on limestone ridges around Dothan; tiny figures on a roof. 9:16, 20mm, no text.",
        "subject_motion": "Tiny figures remain still for scale.",
        "camera_motion": "drone",
        "environment_motion": "embers circulate; clouds crawl",
        "lighting_motion": "golden backlight, stable",
        "facial_motion": "faces too distant to change",
        "camera": "drone",
        "location": "ridges surrounding Dothan",
        "lighting": "golden supernatural backlight",
        "sound_design": "low brass, wind",
        "transition": "dissolve",
        "characters": ["Elisha", "Servant"],
    },
    {
        "scene_id": 8,
        "duration": 7,
        "narration": "What he feared was not the whole story. It never is.",
        "visual_prompt": "Rooftop two-shot: Elisha’s hand on the servant’s shoulder; gold on distant ridges. 9:16, 40mm, no text.",
        "subject_motion": "Hand settles on the shoulder and stays.",
        "camera_motion": "slow dolly-out",
        "environment_motion": "distant fire-glow pulses once",
        "lighting_motion": "soft gold wrap, dimmed valley",
        "facial_motion": "one tear; breathing slows; preserve both faces",
        "camera": "slow dolly-out",
        "location": "rooftop, Dothan",
        "lighting": "soft gold",
        "sound_design": "resolved music",
        "transition": "fade",
        "characters": ["Elisha", "Servant"],
    },
    {
        "scene_id": 9,
        "duration": 7,
        "narration": "Ask for eyes to see. The army of the Lord is already there.",
        "visual_prompt": "Hero portrait of Elisha, gray hair and beard, earth-tone robe, faint luminous ridge behind. 9:16, 50mm, no text.",
        "subject_motion": "Almost still; cloak edge in a breeze.",
        "camera_motion": "static",
        "environment_motion": "background glow breathes 5 percent",
        "lighting_motion": "soft frontal, gold rim",
        "facial_motion": "one slow blink; preserve Elisha",
        "camera": "static",
        "location": "stone terrace",
        "lighting": "soft frontal plus gold rim",
        "sound_design": "held note, silence",
        "transition": "end",
        "characters": ["Elisha"],
    },
]


def plan_from_idea(idea: str, *, duration: int = 60, aspect_ratio: str = "9:16") -> dict:
    text = idea.lower()
    if "elisha" in text or "heavenly army" in text or "dothan" in text:
        scenes = ELISHA_SCENES
        title = "Eyes to See: Elisha and the Heavenly Army"
        script = "\n\n".join(s["narration"] for s in scenes)
        return {
            "title": title,
            "summary": "A 60-second cinematic Bible Short: fear at dawn, then the mountain fills with horses and chariots of fire.",
            "duration": duration,
            "aspect_ratio": aspect_ratio,
            "scenes": scenes,
            "script": script,
        }

    beats = [part.strip() for part in idea.replace(".", ".\n").split("\n") if part.strip()][:8] or [idea]
    each = max(duration / max(len(beats), 1), 4)
    scenes = []
    for i, beat in enumerate(beats, start=1):
        scenes.append(
            {
                "scene_id": i,
                "duration": round(each, 1),
                "narration": beat,
                "visual_prompt": f"{beat}. {aspect_ratio} cinematic still, no text.",
                "subject_motion": "subtle natural movement, preserve identity",
                "camera_motion": "slow dolly-in" if i % 2 else "static",
                "environment_motion": "light atmospheric motion",
                "lighting_motion": "stable motivated light",
                "facial_motion": "one blink, preserve facial structure",
                "camera": "slow dolly-in" if i % 2 else "static",
                "location": "story world",
                "lighting": "cinematic",
                "sound_design": "underscore",
                "transition": "cut",
                "characters": [],
            }
        )
    return {
        "title": idea[:80],
        "summary": idea,
        "duration": duration,
        "aspect_ratio": aspect_ratio,
        "scenes": scenes,
        "script": "\n\n".join(s["narration"] for s in scenes),
    }
