"""Model registry — swap models without changing application services."""

from __future__ import annotations

from typing import Any, Literal

ProviderKind = Literal["local", "cloud", "mock"]
Category = Literal[
    "image_generation",
    "text_to_video",
    "image_to_video",
    "video_to_video",
    "upscaling",
    "tts",
    "speech_to_text",
    "music",
]


def _model(
    *,
    model_id: str,
    display_name: str,
    provider: str,
    location: ProviderKind,
    capabilities: list[str],
    vram_gb: float,
    resolutions: list[str],
    max_duration_seconds: float | None,
    license: str,
    commercial_use: bool,
    estimated_generation_time_seconds: float,
    priority: int,
    enabled: bool = True,
) -> dict[str, Any]:
    return {
        "model_id": model_id,
        "display_name": display_name,
        "provider": provider,
        "location": location,
        "capabilities": capabilities,
        "vram_gb": vram_gb,
        "resolutions": resolutions,
        "max_duration_seconds": max_duration_seconds,
        "license": license,
        "commercial_use": commercial_use,
        "estimated_generation_time_seconds": estimated_generation_time_seconds,
        "priority": priority,
        "enabled": enabled,
    }


MODEL_REGISTRY: dict[Category, list[dict[str, Any]]] = {
    "image_generation": [
        _model(
            model_id="mock-image-v1",
            display_name="Mock Image (dev)",
            provider="remzyforge.mock",
            location="mock",
            capabilities=["text-to-image", "storyboard-still"],
            vram_gb=0,
            resolutions=["720p", "1080p"],
            max_duration_seconds=None,
            license="MIT",
            commercial_use=True,
            estimated_generation_time_seconds=1,
            priority=100,
        ),
        _model(
            model_id="sdxl-base",
            display_name="SDXL-compatible",
            provider="huggingface.diffusers",
            location="local",
            capabilities=["text-to-image", "img2img", "controlnet"],
            vram_gb=8,
            resolutions=["720p", "1080p"],
            max_duration_seconds=None,
            license="CreativeML Open RAIL++-M",
            commercial_use=True,
            estimated_generation_time_seconds=12,
            priority=40,
        ),
        _model(
            model_id="flux-compatible",
            display_name="FLUX-compatible",
            provider="huggingface.diffusers",
            location="local",
            capabilities=["text-to-image"],
            vram_gb=16,
            resolutions=["720p", "1080p"],
            max_duration_seconds=None,
            license="check-upstream",
            commercial_use=False,
            estimated_generation_time_seconds=18,
            priority=30,
            enabled=False,
        ),
    ],
    "text_to_video": [
        _model(
            model_id="mock-t2v-v1",
            display_name="Mock Text-to-Video (dev)",
            provider="remzyforge.mock",
            location="mock",
            capabilities=["text-to-video"],
            vram_gb=0,
            resolutions=["720p", "1080p"],
            max_duration_seconds=12,
            license="MIT",
            commercial_use=True,
            estimated_generation_time_seconds=2,
            priority=100,
        ),
        _model(
            model_id="ltx-video",
            display_name="LTX-Video",
            provider="huggingface.diffusers",
            location="local",
            capabilities=["text-to-video", "image-to-video"],
            vram_gb=12,
            resolutions=["720p"],
            max_duration_seconds=8,
            license="check-upstream",
            commercial_use=True,
            estimated_generation_time_seconds=90,
            priority=50,
        ),
        _model(
            model_id="cogvideox",
            display_name="CogVideoX",
            provider="huggingface.diffusers",
            location="local",
            capabilities=["text-to-video"],
            vram_gb=16,
            resolutions=["720p"],
            max_duration_seconds=6,
            license="Apache-2.0",
            commercial_use=True,
            estimated_generation_time_seconds=120,
            priority=45,
        ),
        _model(
            model_id="hunyuan-video",
            display_name="HunyuanVideo",
            provider="huggingface.diffusers",
            location="local",
            capabilities=["text-to-video"],
            vram_gb=24,
            resolutions=["720p"],
            max_duration_seconds=5,
            license="check-upstream",
            commercial_use=False,
            estimated_generation_time_seconds=180,
            priority=35,
            enabled=False,
        ),
        _model(
            model_id="wan-video",
            display_name="Wan video",
            provider="comfyui",
            location="local",
            capabilities=["text-to-video", "image-to-video"],
            vram_gb=24,
            resolutions=["720p"],
            max_duration_seconds=5,
            license="check-upstream",
            commercial_use=False,
            estimated_generation_time_seconds=200,
            priority=30,
            enabled=False,
        ),
    ],
    "image_to_video": [
        _model(
            model_id="mock-i2v-v1",
            display_name="Mock Image-to-Video (dev)",
            provider="remzyforge.mock",
            location="mock",
            capabilities=["image-to-video", "ken-burns"],
            vram_gb=0,
            resolutions=["720p", "1080p"],
            max_duration_seconds=30,
            license="MIT",
            commercial_use=True,
            estimated_generation_time_seconds=3,
            priority=100,
        ),
        _model(
            model_id="animatediff",
            display_name="AnimateDiff",
            provider="huggingface.diffusers",
            location="local",
            capabilities=["image-to-video", "motion-lora"],
            vram_gb=10,
            resolutions=["720p"],
            max_duration_seconds=4,
            license="Apache-2.0",
            commercial_use=True,
            estimated_generation_time_seconds=60,
            priority=40,
        ),
    ],
    "video_to_video": [
        _model(
            model_id="mock-v2v-v1",
            display_name="Mock Video-to-Video (dev)",
            provider="remzyforge.mock",
            location="mock",
            capabilities=["video-to-video"],
            vram_gb=0,
            resolutions=["720p", "1080p"],
            max_duration_seconds=30,
            license="MIT",
            commercial_use=True,
            estimated_generation_time_seconds=3,
            priority=100,
        ),
    ],
    "upscaling": [
        _model(
            model_id="mock-upscale-v1",
            display_name="Mock Upscale (dev)",
            provider="remzyforge.mock",
            location="mock",
            capabilities=["upscale-2x"],
            vram_gb=0,
            resolutions=["1080p"],
            max_duration_seconds=None,
            license="MIT",
            commercial_use=True,
            estimated_generation_time_seconds=2,
            priority=100,
        ),
    ],
    "tts": [
        _model(
            model_id="mock-tts-v1",
            display_name="Mock TTS (dev)",
            provider="remzyforge.mock",
            location="mock",
            capabilities=["tts", "scene-aligned"],
            vram_gb=0,
            resolutions=[],
            max_duration_seconds=600,
            license="MIT",
            commercial_use=True,
            estimated_generation_time_seconds=1,
            priority=100,
        ),
        _model(
            model_id="kokoro",
            display_name="Kokoro",
            provider="local.onnx",
            location="local",
            capabilities=["tts"],
            vram_gb=2,
            resolutions=[],
            max_duration_seconds=600,
            license="Apache-2.0",
            commercial_use=True,
            estimated_generation_time_seconds=8,
            priority=50,
        ),
    ],
    "speech_to_text": [
        _model(
            model_id="whisper-base",
            display_name="Whisper Base",
            provider="faster-whisper",
            location="local",
            capabilities=["stt", "word-timestamps", "srt", "vtt"],
            vram_gb=1,
            resolutions=[],
            max_duration_seconds=3600,
            license="MIT",
            commercial_use=True,
            estimated_generation_time_seconds=10,
            priority=50,
        ),
    ],
    "music": [
        _model(
            model_id="mock-music-v1",
            display_name="Mock Music (dev)",
            provider="remzyforge.mock",
            location="mock",
            capabilities=["underscore"],
            vram_gb=0,
            resolutions=[],
            max_duration_seconds=180,
            license="MIT",
            commercial_use=True,
            estimated_generation_time_seconds=2,
            priority=100,
        ),
    ],
}


def list_models(category: Category | None = None, *, include_disabled: bool = False) -> list[dict[str, Any]]:
    cats = [category] if category else list(MODEL_REGISTRY.keys())
    rows: list[dict[str, Any]] = []
    for cat in cats:
        for item in MODEL_REGISTRY[cat]:
            if item["enabled"] or include_disabled:
                rows.append({**item, "category": cat})
    return sorted(rows, key=lambda r: (-r["priority"], r["model_id"]))
